name: CI + Push to AWS ECR

on:
  push:
    branches: ["main"]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Login to AWS ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build Docker image
        run: |
          docker build -t flask-app ./flask-docker-app

      - name: Tag Docker image for ECR
        run: |
          docker tag flask-app:latest \
          123456789012.dkr.ecr.ap-south-1.amazonaws.com/flask-app:latest

      - name: Push image to AWS ECR
        run: |
          docker push \
          123456789012.dkr.ecr.ap-south-1.amazonaws.com/flask-app:latest

      - name: Pipeline summary
        run: |
          echo "Build successful"
          echo "Image pushed to AWS ECR"
        

